import pandas as pd
from fpdf import FPDF
import datetime
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'FinShield AI - Security Scan Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

class ReportGenerator:
    """
    Generates downloadable PDF/CSV reports for security audits.
    """
    
    @staticmethod
    def generate_csv(data_list):
        df = pd.DataFrame(data_list)
        return df.to_csv(index=False).encode('utf-8')

    @staticmethod
    def generate_pdf(scan_results, username):
        pdf = PDFReport()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        
        # Meta Info
        pdf.cell(200, 10, txt=f"Generated By: {username}", ln=True)
        pdf.cell(200, 10, txt=f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.ln(10)
        
        # Summary Table
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(40, 10, "Risk Level", 1)
        pdf.cell(100, 10, "URL", 1)
        pdf.cell(40, 10, "Confidence", 1)
        pdf.ln()
        
        pdf.set_font("Arial", size=10)
        for item in scan_results:
            url = item['url'][:50] + "..." if len(item['url']) > 50 else item['url']

            conf = item.get("confidence")
            if conf is None:
                conf = item.get("prob_phishing", 0.0)
            pdf.cell(40, 10, str(item['risk']), 1)
            pdf.cell(100, 10, url, 1)
            pdf.cell(40, 10, f"{float(conf):.2%}", 1)
            pdf.ln()
            
        # Ensure directory exists
        os.makedirs("data/reports", exist_ok=True)
        filename = f"data/reports/scan_report_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        pdf.output(filename)
        return filename

    @staticmethod
    def generate_certificate(username, level, score, total):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 20)
        pdf.cell(0, 15, "FinShield AI Certificate of Completion", ln=True, align="C")
        pdf.ln(6)
        pdf.set_font("Arial", size=12)
        pdf.multi_cell(
            0,
            8,
            f"This certifies that {username} has successfully completed the Cybersecurity Awareness Quiz ({level}) with a score of {score}/{total}.",
            align="C",
        )
        pdf.ln(4)
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 8, f"Issue Date (UTC): {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        os.makedirs("data/certificates", exist_ok=True)
        filename = f"data/certificates/certificate_{username}_{datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S')}.pdf"
        pdf.output(filename)
        return filename
